//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSwipeAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int EmployeeId { get; set; }
        public int CardId { get; set; }
        public string UserType { get; set; }
    }
}
